/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zlistx */

#ifndef _Included_org_zeromq_czmq_Zlistx
#define _Included_org_zeromq_czmq_Zlistx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __unpack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1unpack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlistx__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __addStart
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1addStart
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __addEnd
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1addEnd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __head
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1head
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __tail
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1tail
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __first
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __prev
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1prev
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __last
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1last
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __item
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1item
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __cursor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1cursor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __handleItem
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1handleItem
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __find
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1find
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __detach
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1detach
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __detachCur
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1detachCur
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __delete
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zlistx__1_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __moveStart
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlistx__1_1moveStart
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __moveEnd
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlistx__1_1moveEnd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __purge
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlistx__1_1purge
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __sort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlistx__1_1sort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __insert
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1insert
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __reorder
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlistx__1_1reorder
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __pack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlistx__1_1pack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlistx
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlistx__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
