/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zdigest */

#ifndef _Included_org_zeromq_czmq_Zdigest
#define _Included_org_zeromq_czmq_Zdigest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zdigest
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdigest__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zdigest
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdigest__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdigest
 * Method:    __update
 * Signature: (J[BJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdigest__1_1update
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zdigest
 * Method:    __data
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zeromq_czmq_Zdigest__1_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdigest
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdigest__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdigest
 * Method:    __string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zdigest__1_1string
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdigest
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdigest__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
