/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_ZhttpResponse */

#ifndef _Included_org_zeromq_czmq_ZhttpResponse
#define _Included_org_zeromq_czmq_ZhttpResponse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __send
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1send
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __recv
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1recv
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __contentType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1contentType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __setContentType
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1setContentType
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __statusCode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1statusCode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __setStatusCode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1setStatusCode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __headers
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1headers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __contentLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1contentLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __content
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1content
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __getContent
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1getContent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __setContentConst
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1setContentConst
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __resetContent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1resetContent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpResponse
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpResponse__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
