/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Ztrie */

#ifndef _Included_org_zeromq_czmq_Ztrie
#define _Included_org_zeromq_czmq_Ztrie
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __new
 * Signature: (C)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ztrie__1_1new
  (JNIEnv *, jclass, jchar);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ztrie__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __removeRoute
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Ztrie__1_1removeRoute
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __matches
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Ztrie__1_1matches
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __hitData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ztrie__1_1hitData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __hitParameterCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ztrie__1_1hitParameterCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __hitParameters
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ztrie__1_1hitParameters
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __hitAsteriskMatch
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Ztrie__1_1hitAsteriskMatch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ztrie__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztrie
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ztrie__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
