/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zmsg */

#ifndef _Included_org_zeromq_czmq_Zmsg
#define _Included_org_zeromq_czmq_Zmsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __recv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1recv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __decode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1decode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __newSignal
 * Signature: (B)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1newSignal
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zmsg__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __send
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1send
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __sendm
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1sendm
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __contentSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1contentSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __routingId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1routingId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __setRoutingId
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zmsg__1_1setRoutingId
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __prepend
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1prepend
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __append
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1append
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __pop
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1pop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __pushmem
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1pushmem
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __addmem
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1addmem
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __pushstr
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1pushstr
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __addstr
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1addstr
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __pushstrf
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1pushstrf
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __addstrf
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1addstrf
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __popstr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zmsg__1_1popstr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __addmsg
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1addmsg
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __popmsg
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1popmsg
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __remove
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zmsg__1_1remove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __first
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __last
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1last
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __encode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1encode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zmsg__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zmsg__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __eq
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zmsg__1_1eq
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __signal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zmsg__1_1signal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __is
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zmsg__1_1is
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zmsg
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zmsg__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
