/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_ZdirPatch */

#ifndef _Included_org_zeromq_czmq_ZdirPatch
#define _Included_org_zeromq_czmq_ZdirPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __new
 * Signature: (Ljava/lang/String;JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1new
  (JNIEnv *, jclass, jstring, jlong, jint, jstring);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __path
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1path
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __file
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1file
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __op
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1op
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __vpath
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1vpath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __digestSet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1digestSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __digest
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1digest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZdirPatch
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZdirPatch__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
