/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Ztimerset */

#ifndef _Included_org_zeromq_czmq_Ztimerset
#define _Included_org_zeromq_czmq_Ztimerset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ztimerset__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ztimerset__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __cancel
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Ztimerset__1_1cancel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __setInterval
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Ztimerset__1_1setInterval
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __reset
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Ztimerset__1_1reset
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __timeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Ztimerset__1_1timeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __execute
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Ztimerset__1_1execute
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ztimerset
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ztimerset__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
