/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zclock */

#ifndef _Included_org_zeromq_czmq_Zclock
#define _Included_org_zeromq_czmq_Zclock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zclock
 * Method:    __sleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zclock__1_1sleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zclock
 * Method:    __time
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zclock__1_1time
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zclock
 * Method:    __mono
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zclock__1_1mono
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zclock
 * Method:    __usecs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zclock__1_1usecs
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zclock
 * Method:    __timestr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zclock__1_1timestr
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zclock
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zclock__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
