/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zsock */

#ifndef _Included_org_zeromq_czmq_Zsock
#define _Included_org_zeromq_czmq_Zsock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __new
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newPub
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newPub
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newSub
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newSub
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newReq
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newReq
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newRep
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newRep
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newDealer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newDealer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newRouter
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newRouter
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newPush
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newPush
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newPull
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newPull
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newXpub
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newXpub
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newXsub
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newXsub
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newPair
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newPair
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newStream
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newStream
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newServer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newServer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newClient
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newClient
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newRadio
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newRadio
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newDish
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newDish
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newGather
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newGather
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __newScatter
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1newScatter
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __bind
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1bind
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __endpoint
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1endpoint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __unbind
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1unbind
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __connect
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1connect
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __disconnect
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1disconnect
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __attach
 * Signature: (JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1attach
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __typeStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1typeStr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __send
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1send
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __recv
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1recv
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __bsend
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1bsend
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __brecv
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1brecv
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __routingId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1routingId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRoutingId
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRoutingId
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setUnbounded
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setUnbounded
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __signal
 * Signature: (JB)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1signal
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __wait
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1wait
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __join
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1join
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __leave
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1leave
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __is
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zsock__1_1is
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __resolve
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsock__1_1resolve
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __hasIn
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zsock__1_1hasIn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __routerNotify
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1routerNotify
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRouterNotify
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRouterNotify
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __multicastLoop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1multicastLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setMulticastLoop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setMulticastLoop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __metadata
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1metadata
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setMetadata
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setMetadata
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __loopbackFastpath
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1loopbackFastpath
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setLoopbackFastpath
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setLoopbackFastpath
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __zapEnforceDomain
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1zapEnforceDomain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setZapEnforceDomain
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setZapEnforceDomain
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __gssapiPrincipalNametype
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1gssapiPrincipalNametype
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setGssapiPrincipalNametype
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setGssapiPrincipalNametype
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __gssapiServicePrincipalNametype
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1gssapiServicePrincipalNametype
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setGssapiServicePrincipalNametype
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setGssapiServicePrincipalNametype
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __bindtodevice
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1bindtodevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setBindtodevice
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setBindtodevice
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __heartbeatIvl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1heartbeatIvl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setHeartbeatIvl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setHeartbeatIvl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __heartbeatTtl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1heartbeatTtl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setHeartbeatTtl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setHeartbeatTtl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __heartbeatTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1heartbeatTimeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setHeartbeatTimeout
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setHeartbeatTimeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __useFd
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1useFd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setUseFd
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setUseFd
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setXpubManual
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setXpubManual
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setXpubWelcomeMsg
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setXpubWelcomeMsg
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setStreamNotify
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setStreamNotify
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __invertMatching
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1invertMatching
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setInvertMatching
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setInvertMatching
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setXpubVerboser
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setXpubVerboser
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __connectTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1connectTimeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setConnectTimeout
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setConnectTimeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __tcpMaxrt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1tcpMaxrt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setTcpMaxrt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setTcpMaxrt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __threadSafe
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1threadSafe
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __multicastMaxtpdu
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1multicastMaxtpdu
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setMulticastMaxtpdu
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setMulticastMaxtpdu
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __vmciBufferSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1vmciBufferSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setVmciBufferSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setVmciBufferSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __vmciBufferMinSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1vmciBufferMinSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setVmciBufferMinSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setVmciBufferMinSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __vmciBufferMaxSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1vmciBufferMaxSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setVmciBufferMaxSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setVmciBufferMaxSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __vmciConnectTimeout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1vmciConnectTimeout
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setVmciConnectTimeout
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setVmciConnectTimeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __tos
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1tos
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setTos
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setTos
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRouterHandover
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRouterHandover
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setConnectRid
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setConnectRid
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setConnectRidBin
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setConnectRidBin
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __handshakeIvl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1handshakeIvl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setHandshakeIvl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setHandshakeIvl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __socksProxy
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1socksProxy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setSocksProxy
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setSocksProxy
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setXpubNodrop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setXpubNodrop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRouterMandatory
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRouterMandatory
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setProbeRouter
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setProbeRouter
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setReqRelaxed
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setReqRelaxed
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setReqCorrelate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setReqCorrelate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setConflate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setConflate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __zapDomain
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1zapDomain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setZapDomain
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setZapDomain
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __mechanism
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1mechanism
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __plainServer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1plainServer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setPlainServer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setPlainServer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __plainUsername
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1plainUsername
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setPlainUsername
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setPlainUsername
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __plainPassword
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1plainPassword
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setPlainPassword
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setPlainPassword
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __curveServer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1curveServer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setCurveServer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setCurveServer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __curvePublickey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1curvePublickey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setCurvePublickey
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setCurvePublickey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setCurvePublickeyBin
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setCurvePublickeyBin
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __curveSecretkey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1curveSecretkey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setCurveSecretkey
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setCurveSecretkey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setCurveSecretkeyBin
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setCurveSecretkeyBin
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __curveServerkey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1curveServerkey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setCurveServerkey
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setCurveServerkey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setCurveServerkeyBin
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setCurveServerkeyBin
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __gssapiServer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1gssapiServer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setGssapiServer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setGssapiServer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __gssapiPlaintext
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1gssapiPlaintext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setGssapiPlaintext
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setGssapiPlaintext
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __gssapiPrincipal
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1gssapiPrincipal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setGssapiPrincipal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setGssapiPrincipal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __gssapiServicePrincipal
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1gssapiServicePrincipal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setGssapiServicePrincipal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setGssapiServicePrincipal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __ipv6
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1ipv6
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setIpv6
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setIpv6
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __immediate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1immediate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setImmediate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setImmediate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __sndhwm
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1sndhwm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setSndhwm
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setSndhwm
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __rcvhwm
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1rcvhwm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRcvhwm
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRcvhwm
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __maxmsgsize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1maxmsgsize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setMaxmsgsize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setMaxmsgsize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __multicastHops
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1multicastHops
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setMulticastHops
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setMulticastHops
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setXpubVerbose
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setXpubVerbose
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __tcpKeepalive
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1tcpKeepalive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setTcpKeepalive
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setTcpKeepalive
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __tcpKeepaliveIdle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1tcpKeepaliveIdle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setTcpKeepaliveIdle
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setTcpKeepaliveIdle
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __tcpKeepaliveCnt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1tcpKeepaliveCnt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setTcpKeepaliveCnt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setTcpKeepaliveCnt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __tcpKeepaliveIntvl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1tcpKeepaliveIntvl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setTcpKeepaliveIntvl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setTcpKeepaliveIntvl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __tcpAcceptFilter
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1tcpAcceptFilter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setTcpAcceptFilter
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setTcpAcceptFilter
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __lastEndpoint
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1lastEndpoint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRouterRaw
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRouterRaw
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __ipv4only
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1ipv4only
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setIpv4only
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setIpv4only
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setDelayAttachOnConnect
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setDelayAttachOnConnect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __hwm
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1hwm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setHwm
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setHwm
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __swap
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1swap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setSwap
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setSwap
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __affinity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1affinity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setAffinity
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setAffinity
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __identity
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsock__1_1identity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setIdentity
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setIdentity
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __rate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1rate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __recoveryIvl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1recoveryIvl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRecoveryIvl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRecoveryIvl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __recoveryIvlMsec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1recoveryIvlMsec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRecoveryIvlMsec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRecoveryIvlMsec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __mcastLoop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1mcastLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setMcastLoop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setMcastLoop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __rcvtimeo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1rcvtimeo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRcvtimeo
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRcvtimeo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __sndtimeo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1sndtimeo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setSndtimeo
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setSndtimeo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __sndbuf
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1sndbuf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setSndbuf
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setSndbuf
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __rcvbuf
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1rcvbuf
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setRcvbuf
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setRcvbuf
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __linger
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1linger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setLinger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setLinger
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __reconnectIvl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1reconnectIvl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setReconnectIvl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setReconnectIvl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __reconnectIvlMax
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1reconnectIvlMax
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setReconnectIvlMax
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setReconnectIvlMax
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __backlog
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1backlog
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setBacklog
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setBacklog
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setSubscribe
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setSubscribe
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __setUnsubscribe
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1setUnsubscribe
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __rcvmore
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1rcvmore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __events
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsock__1_1events
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsock
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsock__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
