/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zconfig */

#ifndef _Included_org_zeromq_czmq_Zconfig
#define _Included_org_zeromq_czmq_Zconfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __new
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1new
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __load
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1load
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __loadf
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1loadf
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zconfig__1_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __value
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zconfig__1_1value
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __put
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1put
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __putf
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1putf
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __get
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zconfig__1_1get
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __setName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1setName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __setValue
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1setValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __child
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1child
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __locate
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1locate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __atDepth
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1atDepth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __setComment
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1setComment
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __comments
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1comments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __save
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zconfig__1_1save
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __savef
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zconfig__1_1savef
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __filename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zconfig__1_1filename
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __reload
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1reload
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __chunkLoad
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1chunkLoad
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __chunkSave
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1chunkSave
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __strLoad
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1strLoad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __strSave
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zconfig__1_1strSave
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __hasChanged
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zconfig__1_1hasChanged
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __removeSubtree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1removeSubtree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __remove
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zconfig__1_1remove
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zconfig
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zconfig__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
