/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zchunk */

#ifndef _Included_org_zeromq_czmq_Zchunk
#define _Included_org_zeromq_czmq_Zchunk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __new
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1new
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zchunk__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __resize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zchunk__1_1resize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __maxSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1maxSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __data
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zeromq_czmq_Zchunk__1_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __set
 * Signature: (J[BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1set
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __fill
 * Signature: (JBJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1fill
  (JNIEnv *, jclass, jlong, jbyte, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __append
 * Signature: (J[BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1append
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __extend
 * Signature: (J[BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1extend
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __consume
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1consume
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __exhausted
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zchunk__1_1exhausted
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __slurp
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1slurp
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __strhex
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zchunk__1_1strhex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __strdup
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zchunk__1_1strdup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __streq
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zchunk__1_1streq
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __pack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1pack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __packx
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1packx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __unpack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zchunk__1_1unpack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __digest
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zchunk__1_1digest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zchunk__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __is
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zchunk__1_1is
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zchunk
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zchunk__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
