/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zframe */

#ifndef _Included_org_zeromq_czmq_Zframe
#define _Included_org_zeromq_czmq_Zframe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __new
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zframe__1_1new
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __newEmpty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zframe__1_1newEmpty
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __from
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zframe__1_1from
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __recv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zframe__1_1recv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zframe__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __send
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zframe__1_1send
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zframe__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __data
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zeromq_czmq_Zframe__1_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __meta
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zframe__1_1meta
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zframe__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __strhex
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zframe__1_1strhex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __strdup
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zframe__1_1strdup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __streq
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zframe__1_1streq
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __more
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zframe__1_1more
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __setMore
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zframe__1_1setMore
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __routingId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zframe__1_1routingId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __setRoutingId
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zframe__1_1setRoutingId
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __group
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zframe__1_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __setGroup
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zframe__1_1setGroup
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __eq
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zframe__1_1eq
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __reset
 * Signature: (J[BJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zframe__1_1reset
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __print
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zframe__1_1print
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __is
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zframe__1_1is
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zframe
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zframe__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
