/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_ZhttpServer */

#ifndef _Included_org_zeromq_czmq_ZhttpServer
#define _Included_org_zeromq_czmq_ZhttpServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_ZhttpServer
 * Method:    __new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpServer__1_1new
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpServer
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpServer__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpServer
 * Method:    __port
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_ZhttpServer__1_1port
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpServer
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpServer__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
