/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_ZhttpServerOptions */

#ifndef _Included_org_zeromq_czmq_ZhttpServerOptions
#define _Included_org_zeromq_czmq_ZhttpServerOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __fromConfig
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1fromConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __port
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1port
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __setPort
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1setPort
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __backendAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1backendAddress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __setBackendAddress
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1setBackendAddress
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpServerOptions
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpServerOptions__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
