/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zloop */

#ifndef _Included_org_zeromq_czmq_Zloop
#define _Included_org_zeromq_czmq_Zloop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zloop__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __readerEnd
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1readerEnd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __readerSetTolerant
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1readerSetTolerant
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __timerEnd
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zloop__1_1timerEnd
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __ticketReset
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1ticketReset
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __ticketDelete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1ticketDelete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __setTicketDelay
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1setTicketDelay
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __setMaxTimers
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1setMaxTimers
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __setVerbose
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1setVerbose
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __setNonstop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1setNonstop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zloop__1_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zloop
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zloop__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
