/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Ziflist */

#ifndef _Included_org_zeromq_czmq_Ziflist
#define _Included_org_zeromq_czmq_Ziflist
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ziflist__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ziflist__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __reload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ziflist__1_1reload
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ziflist__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __first
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Ziflist__1_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __next
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Ziflist__1_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __address
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Ziflist__1_1address
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __broadcast
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Ziflist__1_1broadcast
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __netmask
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Ziflist__1_1netmask
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ziflist__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __newIpv6
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Ziflist__1_1newIpv6
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __reloadIpv6
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ziflist__1_1reloadIpv6
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __isIpv6
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Ziflist__1_1isIpv6
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Ziflist
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Ziflist__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
