/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zcertstore */

#ifndef _Included_org_zeromq_czmq_Zcertstore
#define _Included_org_zeromq_czmq_Zcertstore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __new
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcertstore__1_1new
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcertstore__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __lookup
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcertstore__1_1lookup
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __insert
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcertstore__1_1insert
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __empty
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcertstore__1_1empty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcertstore__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __certs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcertstore__1_1certs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcertstore
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcertstore__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
