/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zarmour */

#ifndef _Included_org_zeromq_czmq_Zarmour
#define _Included_org_zeromq_czmq_Zarmour
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zarmour__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __encode
 * Signature: (J[BJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zarmour__1_1encode
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __decode
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zarmour__1_1decode
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __mode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zarmour__1_1mode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __modeStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zarmour__1_1modeStr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __setMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1setMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __pad
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zarmour__1_1pad
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __setPad
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1setPad
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __padChar
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_org_zeromq_czmq_Zarmour__1_1padChar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __setPadChar
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1setPadChar
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __lineBreaks
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zarmour__1_1lineBreaks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __setLineBreaks
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1setLineBreaks
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __lineLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zarmour__1_1lineLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __setLineLength
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1setLineLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zarmour
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zarmour__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
