/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zstr */

#ifndef _Included_org_zeromq_czmq_Zstr
#define _Included_org_zeromq_czmq_Zstr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __recv
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zstr__1_1recv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __recvCompress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zstr__1_1recvCompress
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __send
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zstr__1_1send
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __sendm
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zstr__1_1sendm
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __sendf
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zstr__1_1sendf
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __sendfm
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zstr__1_1sendfm
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __sendx
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zstr__1_1sendx
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __sendCompress
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zstr__1_1sendCompress
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __sendmCompress
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zstr__1_1sendmCompress
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __str
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zstr__1_1str
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zstr
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zstr__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
