/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_ZhttpClient */

#ifndef _Included_org_zeromq_czmq_ZhttpClient
#define _Included_org_zeromq_czmq_ZhttpClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_ZhttpClient
 * Method:    __new
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpClient__1_1new
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeromq_czmq_ZhttpClient
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpClient__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpClient
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpClient__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
