/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zcert */

#ifndef _Included_org_zeromq_czmq_Zcert
#define _Included_org_zeromq_czmq_Zcert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcert__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __newFrom
 * Signature: ([B[B)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcert__1_1newFrom
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __newFromTxt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcert__1_1newFromTxt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __load
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcert__1_1load
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcert__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __publicKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zeromq_czmq_Zcert__1_1publicKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __secretKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zeromq_czmq_Zcert__1_1secretKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __publicTxt
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zcert__1_1publicTxt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __secretTxt
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zcert__1_1secretTxt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __setMeta
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcert__1_1setMeta
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __unsetMeta
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcert__1_1unsetMeta
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __meta
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zcert__1_1meta
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __metaKeys
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcert__1_1metaKeys
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __save
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zcert__1_1save
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __savePublic
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zcert__1_1savePublic
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __saveSecret
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zcert__1_1saveSecret
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __apply
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcert__1_1apply
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zcert__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __eq
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zcert__1_1eq
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __print
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcert__1_1print
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zcert
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zcert__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
