/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zhashx */

#ifndef _Included_org_zeromq_czmq_Zhashx
#define _Included_org_zeromq_czmq_Zhashx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __unpack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1unpack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhashx__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __insert
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhashx__1_1insert
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __update
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhashx__1_1update
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhashx__1_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __purge
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhashx__1_1purge
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __lookup
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1lookup
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __rename
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhashx__1_1rename
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __keys
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1keys
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __values
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1values
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __first
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __cursor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1cursor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __comment
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhashx__1_1comment
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __save
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhashx__1_1save
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __load
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhashx__1_1load
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __refresh
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhashx__1_1refresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __pack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1pack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __dupV2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhashx__1_1dupV2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhashx
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhashx__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
