/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zlist */

#ifndef _Included_org_zeromq_czmq_Zlist
#define _Included_org_zeromq_czmq_Zlist
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlist__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __first
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __last
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1last
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __head
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1head
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __tail
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1tail
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __item
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1item
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __append
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zlist__1_1append
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __push
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zlist__1_1push
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __pop
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1pop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __exists
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zlist__1_1exists
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __remove
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlist__1_1remove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __purge
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlist__1_1purge
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zlist__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __autofree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlist__1_1autofree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zlist
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zlist__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
