/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zfile */

#ifndef _Included_org_zeromq_czmq_Zfile
#define _Included_org_zeromq_czmq_Zfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __new
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zfile__1_1new
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __tmp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zfile__1_1tmp
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zfile__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zfile__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __filename
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zfile__1_1filename
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __restat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zfile__1_1restat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __modified
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zfile__1_1modified
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __cursize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zfile__1_1cursize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __isDirectory
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zfile__1_1isDirectory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __isRegular
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zfile__1_1isRegular
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __isReadable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zfile__1_1isReadable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __isWriteable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zfile__1_1isWriteable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __isStable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zfile__1_1isStable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __hasChanged
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zfile__1_1hasChanged
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __remove
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zfile__1_1remove
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __input
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zfile__1_1input
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __output
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zfile__1_1output
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __read
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zfile__1_1read
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __eof
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zfile__1_1eof
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __write
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zfile__1_1write
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __readln
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zfile__1_1readln
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zfile__1_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __digest
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zfile__1_1digest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zfile
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zfile__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
