/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zpoller */

#ifndef _Included_org_zeromq_czmq_Zpoller
#define _Included_org_zeromq_czmq_Zpoller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zpoller__1_1new
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zpoller__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __add
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zpoller__1_1add
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __remove
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zpoller__1_1remove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __setNonstop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zpoller__1_1setNonstop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __wait
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zpoller__1_1wait
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __expired
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zpoller__1_1expired
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __terminated
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zpoller__1_1terminated
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zpoller
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zpoller__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
