/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_ZhttpRequest */

#ifndef _Included_org_zeromq_czmq_ZhttpRequest
#define _Included_org_zeromq_czmq_ZhttpRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __recv
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1recv
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __send
 * Signature: (JJIJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1send
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __method
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1method
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __setMethod
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1setMethod
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __url
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1url
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __setUrl
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1setUrl
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __contentType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1contentType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __setContentType
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1setContentType
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __contentLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1contentLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __headers
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1headers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __content
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1content
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __getContent
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1getContent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __setContentConst
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1setContentConst
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __resetContent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1resetContent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __match
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1match
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_ZhttpRequest
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_ZhttpRequest__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
