/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zhash */

#ifndef _Included_org_zeromq_czmq_Zhash
#define _Included_org_zeromq_czmq_Zhash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __unpack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1unpack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhash__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __insert
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhash__1_1insert
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __update
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhash__1_1update
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __delete
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhash__1_1delete
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __lookup
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1lookup
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __rename
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhash__1_1rename
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __dup
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1dup
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __keys
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1keys
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __first
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1first
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __cursor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zhash__1_1cursor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __comment
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhash__1_1comment
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __pack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zhash__1_1pack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __save
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhash__1_1save
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __load
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhash__1_1load
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __refresh
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zhash__1_1refresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __autofree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhash__1_1autofree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zhash
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zhash__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
