/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zdir */

#ifndef _Included_org_zeromq_czmq_Zdir
#define _Included_org_zeromq_czmq_Zdir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __new
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1new
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdir__1_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __path
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zdir__1_1path
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __modified
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1modified
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __cursize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1cursize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __count
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1count
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __list
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1list
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __remove
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdir__1_1remove
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __diff
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1diff
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __resync
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1resync
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __cache
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zdir__1_1cache
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __print
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdir__1_1print
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __watch
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdir__1_1watch
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_zeromq_czmq_Zdir
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zdir__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
