/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_czmq_Zsys */

#ifndef _Included_org_zeromq_czmq_Zsys
#define _Included_org_zeromq_czmq_Zsys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsys__1_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1shutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __socket
 * Signature: (ILjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsys__1_1socket
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __close
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1close
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __sockname
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1sockname
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __createPipe
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsys__1_1createPipe
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __handlerReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1handlerReset
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __catchInterrupts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1catchInterrupts
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __isInterrupted
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zsys__1_1isInterrupted
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setInterrupted
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setInterrupted
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zsys__1_1fileExists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileModified
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsys__1_1fileModified
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileMode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1fileMode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileDelete
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1fileDelete
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileStable
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zsys__1_1fileStable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __dirCreate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1dirCreate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __dirDelete
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1dirDelete
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __dirChange
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1dirChange
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileModePrivate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1fileModePrivate
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileModeDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1fileModeDefault
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __version
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1version
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __sprintfHint
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1sprintfHint
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __sprintf
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1sprintf
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __socketError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1socketError
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __hostname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1hostname
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __daemonize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1daemonize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __runAs
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1runAs
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __hasCurve
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_zeromq_czmq_Zsys__1_1hasCurve
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setIoThreads
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setIoThreads
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setThreadSchedPolicy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setThreadSchedPolicy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setThreadPriority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setThreadPriority
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setThreadNamePrefix
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setThreadNamePrefix
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __threadNamePrefix
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1threadNamePrefix
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __threadAffinityCpuAdd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1threadAffinityCpuAdd
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __threadAffinityCpuRemove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1threadAffinityCpuRemove
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setMaxSockets
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setMaxSockets
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __socketLimit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsys__1_1socketLimit
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setMaxMsgsz
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setMaxMsgsz
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __maxMsgsz
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1maxMsgsz
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setZeroCopyRecv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setZeroCopyRecv
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __zeroCopyRecv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1zeroCopyRecv
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setFileStableAgeMsec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setFileStableAgeMsec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __fileStableAgeMsec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsys__1_1fileStableAgeMsec
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setLinger
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setLinger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setSndhwm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setSndhwm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setRcvhwm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setRcvhwm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setPipehwm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setPipehwm
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __pipehwm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_czmq_Zsys__1_1pipehwm
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setIpv6
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setIpv6
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __ipv6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1ipv6
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setInterface
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setInterface
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __interface
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1interface
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setIpv6Address
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setIpv6Address
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __ipv6Address
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1ipv6Address
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setIpv6McastAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setIpv6McastAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __ipv6McastAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1ipv6McastAddress
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setAutoUseFd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setAutoUseFd
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __autoUseFd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeromq_czmq_Zsys__1_1autoUseFd
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __zprintf
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1zprintf
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __zprintfError
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1zprintfError
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __zplprintf
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1zplprintf
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __zplprintfError
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zeromq_czmq_Zsys__1_1zplprintfError
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setLogident
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setLogident
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setLogsender
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setLogsender
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __setLogsystem
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1setLogsystem
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __error
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1error
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __warning
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1warning
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __notice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1notice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __info
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1info
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __debug
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1debug
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeromq_czmq_Zsys
 * Method:    __test
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_czmq_Zsys__1_1test
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
